#Turbo
#EVENT botSpawn "#1# is a level #2# #*# Female #3#"
#EVENT botSpawn "#1# is a level #2# #*# Male #3#"

Sub Main
	/declare intMembers int outer 0
	/say ^botlist
	/delay 5
	/doevents
/return
| endsub

Sub EVENT_botSpawn(strFull, strName, strJunk, strClass)
	/if (${Group} < 5) {
		/varset intMembers ${Group}
		/say ^botspawn ${strName}
		/delay 2
		/invite ${strName}
		/delay 1s (${Group} > ${intMembers})
	}
/return
| endsub